const Middleware = require("../../middleware/client/category.middleware");
const cart_middleware = require("../../middleware/client/cart.middleware");
const products_router = require("./products.route");
const home_router = require("./home.route");
const search_route = require("./search.route");
const cart_route = require("./cart.route");
const checkout_route = require("./checkout.route");
const user_route = require("./user.route");
const middleware_user = require("../../middleware/client/user.middleware");
module.exports = (app) => {
  app.use(Middleware.categoryMiddleware);
  app.use(cart_middleware.checkcart);
  app.use(middleware_user.infoUser);
  app.use("/", home_router);
  app.use("/products", products_router);
  app.use("/search", search_route);
  app.use("/cart", cart_route);
  app.use("/checkout", checkout_route);
  app.use("/user", user_route);
};
