const express = require("express");
const router = express.Router();
const controller = require("../../controller/client/user.controller");
const validate = require("../../validate/client/user.validate");
router.get("/register", controller.indexRegister);
router.post("/register", validate.registerPost, controller.registerPost);
router.get("/login", controller.indexLogin);
router.post("/login", validate.loginPost, controller.loginPost);
router.get("/logout", controller.logout);
router.get("/password/forgot", controller.forgotPassword);
router.post("/password/forgot", controller.forgotPasswordPost);
module.exports = router;
